// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPISvvKNkbD0xo74c684TC0fK7kQRLbe4',
    appId: '1:853044061342:web:444c7c65a5bd03f38a078f',
    messagingSenderId: '853044061342',
    projectId: 'wallr-f7607',
    authDomain: 'wallr-f7607.firebaseapp.com',
    storageBucket: 'wallr-f7607.firebasestorage.app',
    measurementId: 'G-0HJW7FJRPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdoaRITdwnKt-ibCPQm4XCPG6OcbLhsoU',
    appId: '1:853044061342:android:6728cfe043cf21ab8a078f',
    messagingSenderId: '853044061342',
    projectId: 'wallr-f7607',
    storageBucket: 'wallr-f7607.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0f2Hu-8y955hQ6VE6SaV4QA-qUXtZc8k',
    appId: '1:853044061342:ios:1f73ce35ff5bb5948a078f',
    messagingSenderId: '853044061342',
    projectId: 'wallr-f7607',
    storageBucket: 'wallr-f7607.firebasestorage.app',
    iosBundleId: 'com.example.wallr',
  );
}
